version: '3'

volumes:
  postgres-five_wc_api:
    driver: local
  images:
    driver: local

services:
  api:
    image: five_wc_api:latest
    build: .
    ports:
      - "7161:80"
      - "7162:443"
  db:
    image: postgres
    ports:
      - "6500:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=five_wc_api
    volumes:
      - postgres-five_wc_api:/var/lib/postgresql/data
