name: Docker Image 5WC API CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build 5wcLogin/FiveWCLoginAPI --file Dockerfile --tag my-image-name:$(date +%s)
